### PR TITLE
Feature: support nbconvert  / voila 0.2.0

### PR DESCRIPTION
**Pull request by agoose77**
The 0.2 release of voila uses the new nbconvert 6.x series. This PR implements fixes to support (only) this new version, i.e. it drops support for voila < 0.2.0 and nbconvert < 0.6.0

I'm not entirely sure I constrained the dependencies properly, so I'd appreciate your input here @danielfrg 

Also, I included a fix for #51 

Thanks!

### CODE REVIEW

**Comment by agoose77** [comment]
Maybe hold off on this until I can test for some issues.

**Comment by danielfrg** [comment]
Hi @agoose77 thanks so much for updating it to the new versions, its been on my list.
I will take a look next week!

**Comment by agoose77** [comment]
@danielfrg I think I've finished the PR - I've renamed the template files to `index.html.j2`, and changed the resource behaviour to use nbconvert as a base (with a dist/ directory). Let me know if you have any issues :)

**Comment by agoose77** [comment]
I *think* I've restored the original behaviour. In doing so, I noticed some things:
* The documentation states that files are resolved locally to the notebook. In voila they're resolved from the directory in which the server is being run. In nbconvert, the stylesheet is found from the directory of nbconvert, and doesn't resolve the logo at all.
* HTML exports don't include any tags for the favicon.

Thinking about this, I wonder if we could write some JS to find the resource URL for the current notebook in voila, i.e. `/voila/files/path/to/notebook-dir` to use for loading the custom CSS and custom logo/favicon. Because the logo is handled by React, perhaps we could use a pre-processor to load the data into a script tag, and reference it in the React code.

This would change the current behaviour from loading custom resources relative to the base URL to loading resources against the current notebook. We could then more implement the same behaviour more easily with nbconvert, because we'd just use the paths directly in the `rel`/`src` parameters. It might also be a good idea to pack the logo, custom-css, and favicon into the exported HTML file when using nbconvert, or expose a packing option, so that users can relocate the exported file.

**Comment by danielfrg** [comment]
@agoose77 Thanks for your work on this. I merged it on #55 

I will do more testing and release probably friday, if you have some extra time to test it aswell it would be awesome!

**Pull request closed without merging**
