### PR TITLE
Fix voila JS kernel changes

### PR DESCRIPTION
**Pull request by danielfrg**
Fixes https://github.com/danielfrg/jupyter-flex/issues/79

There was a change in the Voila JS code in one of the new versions that was causing widgets to not render.

### CODE REVIEW

**Comment by tsdev** [comment]
@danielfrg Is the update of the PyPi package will follow? I don't see the new version there.

**Comment by danielfrg** [comment]
Version `0.6.5` is now on PyPI with the fix.

**Comment by manuks481** [comment]
@danielfrg Still facing the same issue on Windows. Any solution?

**Comment by danielfrg** [comment]
Try downgrading the version of `voila` can you add you `pip freeze`?

**Comment by manuks481** [comment]
Here's my pip freeze. I have tried voila versions 0.2.9 to 0.2.6.... None of them is working.
```
anyio==2.2.0
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.3.0
backcall==0.2.0
bleach==3.3.0
certifi==2020.12.5
cffi==1.14.5
colorama==0.4.4
decorator==5.0.7
defusedxml==0.7.1
deprecation==2.1.0
entrypoints==0.3
idna==3.1
ipykernel==5.5.3
ipython==7.23.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==2.11.3
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyter-flex==0.6.5
jupyter-packaging==0.9.2
jupyter-server==1.6.4
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
MarkupSafe==1.1.1
matplotlib-inline==0.1.2
mistune==0.8.4
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.3.0
packaging==20.9
pandocfilters==1.4.3
parso==0.8.2
pickleshare==0.7.5
prometheus-client==0.10.1
prompt-toolkit==3.0.18
pycparser==2.20
Pygments==2.9.0
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pywin32==300
pywinpty==1.0.1
pyzmq==22.0.3
qtconsole==5.1.0
QtPy==1.9.0
Send2Trash==1.5.0
six==1.15.0
sniffio==1.2.0
terminado==0.9.4
testpath==0.4.4
tomlkit==0.7.0
tornado==6.1
traitlets==5.0.5
voila==0.2.6
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
wincertstore==0.2
```

**Comment by danielfrg** [comment]
mmm, could you try `voila==0.2.10` thats what the CI system is using right now and its working with `jupyter-flex==0.6.5`

**Comment by manuks481** [comment]
Same issue again.... Is it working fine on Linux?

**Comment by danielfrg** [comment]
Its working fine on Linux (CI) and Mac (my laptop). I have a hard problem seeing why is this broken on windows since its just Python and JS but i dont have access to a windows machine.

**Comment by manuks481** [comment]
@danielfrg Thanks for the prompt response. I shall try from my Linux machine.
Hope you will soon fix the bugs for Windows.
Great tool anyway. Kudos to your efforts!!

**Pull request merged**
