### PR TITLE
Add voila heartbeat

### PR DESCRIPTION
**Pull request by agoose77**
This is an edit made on the GitHub editor to add the heartbeat function

### CODE REVIEW

**Comment by danielfrg** [comment]
lgtm, is a function with that named called by voila?

**Comment by agoose77** [comment]
The voila js calls it to, although I need to check whether jupyter flex overrides that js

**Comment by danielfrg** [comment]
It kinda does overwrite it but we add it back using requirejs here: https://github.com/danielfrg/jupyter-flex/blob/master/js/src/App/index.js#L65

**Comment by danielfrg** [comment]
thanks!

**Pull request merged**
